// All UI copy, kept in one place so a Hebrew table can be added later by swapping this object.
export const t = {
  // Dates follow the UI language, not the browser's: mixing a Hebrew date into English copy is
  // what happens otherwise. Switch together with the strings when Hebrew is added.
  locale: 'en-US',
  appName: 'MyStocks',
  nav: {
    dashboard: 'Dashboard',
    transactions: 'Transactions',
    label: 'Main',
  },
  theme: {
    label: 'Theme',
    light: 'Light theme',
    dark: 'Dark theme',
    system: 'Use system theme',
  },
  common: {
    loading: 'Loading…',
    unavailable: 'unavailable',
    noValue: '—',
    usd: 'USD',
    loadError: (what: string, message: string) => `Could not load ${what}: ${message}`,
    serverUnreachable: (message: string) => `Could not reach the server: ${message}`,
    gain: 'up',
    loss: 'down',
  },
  wake: {
    title: 'The server is stretching awake…',
    body: 'It naps when nobody is around, so this can take about a minute. Hang tight, it will carry on by itself.',
    gaveUp: "The server didn't respond. Please reload the page in a minute.",
    retryAction: 'The server was still waking up. Please try again in a few seconds.',
  },
  auth: {
    tagline: 'Your friendly ledger for stocks and crypto.',
    welcome: 'Welcome back!',
    welcomeNew: 'Nice to meet you!',
    logIn: 'Log in',
    createAccount: 'Create account',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm password',
    inviteCode: 'Invite code',
    inviteHint: 'Registration is invite-only. Ask the owner for a code.',
    passwordHint: 'At least 8 characters.',
    passwordsMismatch: "Passwords don't match",
    switchToRegister: 'Need an account? Register',
    switchToLogin: 'Have an account? Log in',
  },
  summary: {
    heading: 'Summary',
    marketValue: 'Portfolio value',
    costBasis: 'Cost basis',
    unrealized: 'Unrealized P/L',
    realized: 'Realized P/L',
    dayChange: 'Daily change',
    partialTotals: 'Totals cover priced holdings only.',
    // Friendly, but must still say plainly that these are the last known prices.
    stalePrices:
      "Some prices are catching their breath: we couldn't reach the price provider, so you're seeing the last known prices (each marked with when it was last updated).",
    unpriced: (symbols: string) => `No price available for ${symbols}; excluded from market value and P/L totals.`,
    dayChangeUnavailable: (symbols: string) => `No daily change for ${symbols}.`,
    dayChangeOpenOnly: 'Open positions only.',
  },
  dayChange: {
    sincePreviousClose: 'since previous close',
    rolling24h: 'rolling 24h',
    mixed: 'stocks since previous close, crypto rolling 24h',
    stockReference: (session: string) => `since previous close (session ${session})`,
    cryptoReference: (since: string) => `rolling 24h (from ${since})`,
  },
  allocation: {
    heading: 'Allocation',
    other: 'Other',
    empty: 'No priced holdings to chart.',
    chartLabel: 'Portfolio allocation by market value',
    excludesUnpriced: 'By market value of priced holdings.',
  },
  holdings: {
    heading: 'Holdings',
    empty: 'No open positions.',
    allClosed: 'All positions are closed for now. Your realized P/L is below.',
    symbol: 'Symbol',
    quantity: 'Quantity',
    averageCost: 'Avg cost',
    price: 'Price',
    value: 'Value',
    dayChange: 'Daily change',
    unrealized: 'Unrealized P/L',
    unrealizedPct: '%',
    staleSince: (when: string) => `last known price · stale since ${when}`,
    footnote: 'Average cost includes buy fees. Daily change is price-only (fees excluded).',
  },
  realized: {
    heading: 'Realized trades',
    empty: 'No sells yet. Realized P/L shows up here after your first sale.',
    date: 'Date',
    symbol: 'Symbol',
    quantity: 'Quantity',
    sellPrice: 'Sell price',
    fee: 'Fee',
    averageCost: 'Avg cost at sale',
    proceeds: 'Proceeds',
    realized: 'Realized P/L',
    footnote: 'Proceeds are net of the sell fee. Realized P/L = proceeds − average cost × quantity.',
  },
  empty: {
    title: 'Your ledger is ready for its first entry',
    body: "Add a buy you've made and MyStocks will keep track of its value, P/L and allocation for you.",
    action: 'Add your first transaction',
  },
  celebration: {
    // One time only, for the first entry. Never tied to gains, losses or trading activity.
    title: 'Your first entry is in the ledger!',
    body: 'From here on, MyStocks keeps the numbers tidy for you.',
    dismiss: 'Close',
  },
  transactions: {
    addHeading: 'Add transaction',
    listHeading: 'Transactions',
    empty: 'Nothing here yet. Your entries will show up in this list.',
    executed: 'Executed',
    symbol: 'Symbol',
    type: 'Type',
    side: 'Side',
    quantity: 'Quantity',
    price: 'Price',
    fee: 'Fee',
    actions: 'Actions',
    delete: 'Delete',
    deleteLabel: (symbol: string, when: string) => `Delete ${symbol} transaction from ${when}`,
    confirmDelete: {
      title: 'Delete this transaction?',
      summary: (side: string, quantity: string, symbol: string, price: string, currency: string, when: string) =>
        `${side} ${quantity} ${symbol} at ${price} ${currency} on ${when}`,
      continue: 'Delete…',
      cancel: 'Cancel',
      confirmTitle: 'Are you sure?',
      confirmBody:
        'This permanently removes the transaction and recalculates your holdings and P/L. It cannot be undone.',
      laterSellsWarning: (symbol: string) =>
        `Careful: you have later sells of ${symbol}. Without this buy they may no longer be covered, and your portfolio will show an error until you fix them.`,
      confirm: 'Yes, delete permanently',
      keep: 'Keep it',
      deleting: 'Deleting…',
      step: (current: number, total: number) => `Step ${current} of ${total}`,
    },
    assetTypes: { stock: 'Stock', crypto: 'Crypto' },
    sides: { buy: 'Buy', sell: 'Sell' },
  },
  form: {
    symbol: 'Symbol',
    symbolPlaceholder: 'Search stocks & crypto',
    type: 'Type',
    side: 'Side',
    executedAt: 'Executed at',
    quantity: 'Quantity',
    price: 'Price (USD)',
    fee: 'Fee (USD)',
    submit: 'Add transaction',
    oversell: (held: string, symbol: string) => `You only hold ${held} ${symbol}.`,
    lookingUp: 'Looking up the price…',
    autofillFailed: (message: string) => `Couldn't auto-fill the price: ${message}`,
    enterManually: ' Enter the price manually.',
    livePrice: 'live price',
    closeOn: (date: string) => `${date} close`,
    autoFilled: (price: string, source: string) => `Auto-filled ${price} USD (${source}).`,
    lookedUp: (price: string, source: string) => `Looked-up price: ${price} USD (${source}).`,
    searchUnavailable: (message: string) =>
      `Search unavailable (${message}). Type the symbol and pick its type.`,
    sourceUnavailable: (assetType: 'stock' | 'crypto', detail: string) =>
      `${assetType === 'stock' ? 'Stock' : 'Crypto'} search unavailable: ${detail}`,
  },
  disclaimer: [
    'Cost basis: average cost; buy fees add to cost, sell fees reduce proceeds. All amounts in USD.',
    'Prices come from free third-party APIs (Finnhub, CoinGecko), are refreshed about once a minute and may be delayed.',
    'For educational and personal tracking use only. Not financial advice.',
  ],
}
