// All UI copy, kept in one place so a Hebrew table can be added later by swapping this object.
export const t = {
  // Dates follow the UI language, not the browser's: mixing a Hebrew date into English copy is
  // what happens otherwise. Switch together with the strings when Hebrew is added.
  locale: 'en-US',
  appName: 'MyStocks',
  nav: {
    dashboard: 'Dashboard',
    transactions: 'Transactions',
    label: 'Main',
  },
  theme: {
    label: 'Theme',
    light: 'Light theme',
    dark: 'Dark theme',
  },
  common: {
    loading: 'Loading…',
    unavailable: 'unavailable',
    noValue: '—',
    usd: 'USD',
    loadError: (what: string, message: string) => `Could not load ${what}: ${message}`,
    serverUnreachable: (message: string) => `Could not reach the server: ${message}`,
    gain: 'up',
    loss: 'down',
  },
  wake: {
    title: 'The server is stretching awake…',
    body: 'It naps when nobody is around, so this can take about a minute. Hang tight, it will carry on by itself.',
    gaveUp: "The server didn't respond. Please reload the page in a minute.",
    retryAction: 'The server was still waking up. Please try again in a few seconds.',
  },
  auth: {
    tagline: 'Your friendly ledger for stocks and crypto.',
    welcome: 'Welcome back!',
    welcomeNew: 'Nice to meet you!',
    logIn: 'Log in',
    createAccount: 'Create account',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm password',
    inviteCode: 'Invite code',
    inviteHint: 'Registration is invite-only. Ask the owner for a code.',
    passwordHint: 'At least 8 characters.',
    passwordsMismatch: "Passwords don't match",
    switchToRegister: 'Need an account? Register',
    switchToLogin: 'Have an account? Log in',
    sessionExpired: 'Your session timed out, so nothing was saved. Log in again and pick up where you left off.',
  },
  writeErrors: {
    rejected: (detail: string) => `That didn't go through: ${detail}`,
    forbidden: "You're not allowed to do that. Try reloading the page.",
    tooMany: (seconds: number | null) =>
      seconds
        ? `Too many attempts in a row. Please wait ${seconds} second${seconds === 1 ? '' : 's'} and try again.`
        : 'Too many attempts in a row. Please wait a moment and try again.',
    failed: (detail: string) => `Something went wrong on our side (${detail}). Please try again.`,
  },
  summary: {
    heading: 'Summary',
    marketValue: 'Portfolio value',
    costBasis: 'Cost basis',
    unrealized: 'Unrealized P/L',
    realized: 'Realized P/L',
    dayChange: 'Daily change',
    partialTotals: 'Totals cover priced holdings only.',
    // Friendly, but must still say plainly that these are the last known prices.
    stalePrices:
      "Some prices are catching their breath: we couldn't reach the price provider, so you're seeing the last known prices (each marked with when it was last updated).",
    unpriced: (symbols: string) => `No price available for ${symbols}; excluded from market value and P/L totals.`,
    notOnDeployment: (symbols: string) =>
      `Stock prices aren't available on this deployment (${symbols}): those holdings show cost basis only. Value and P/L cover priced holdings; "Cost basis (all)" also includes the unpriced ones, so subtracting one from the other doesn't give a P/L.`,
    marketValuePriced: 'Portfolio value (priced holdings)',
    costBasisAll: 'Cost basis (all)',
    unrealizedPriced: 'Unrealized P/L (priced)',
    pricedCostBasis: (amount: string) => `Priced holdings: ${amount} USD (what P/L is measured against)`,
    dayChangeUnavailable: (symbols: string) => `No daily change for ${symbols}.`,
    dayChangeOpenOnly: 'Open positions only.',
  },
  dayChange: {
    sincePreviousClose: 'since previous close',
    rolling24h: 'rolling 24h',
    mixed: 'stocks since previous close, crypto rolling 24h',
    stockReference: (session: string) => `since previous close (session ${session})`,
    cryptoReference: (since: string) => `rolling 24h (from ${since})`,
  },
  allocation: {
    heading: 'Allocation',
    other: 'Other',
    empty: 'No priced holdings to chart.',
    chartLabel: 'Portfolio allocation by market value',
    excludesUnpriced: 'By market value of priced holdings.',
  },
  holdings: {
    heading: 'Holdings',
    empty: 'No open positions.',
    allClosed: 'All positions are closed for now. Your realized P/L is below.',
    symbol: 'Symbol',
    quantity: 'Quantity',
    averageCost: 'Avg cost',
    price: 'Price',
    value: 'Value',
    dayChange: 'Daily change',
    unrealized: 'Unrealized P/L',
    unrealizedPct: '%',
    staleSince: (when: string) => `last known price · stale since ${when}`,
    footnote: 'Average cost includes buy fees. Daily change is price-only (fees excluded).',
    actions: 'Actions',
    sell: 'Sell',
    sellLabel: (symbol: string) => `Sell ${symbol}`,
  },
  sell: {
    title: (symbol: string) => `Sell ${symbol}`,
    held: (quantity: string, symbol: string) => `You hold ${quantity} ${symbol}`,
    quantity: 'Quantity to sell',
    quickLabel: 'Quick amounts',
    quarter: '25%',
    half: '50%',
    all: 'All',
    tooSmall: (pct: string) => `${pct} of this position rounds down to 0 at 10 decimal places. Type an amount or use All.`,
    tooSmallBoth: '25% and 50% of this position round down to 0 at 10 decimal places. Type an amount or use All.',
    price: 'Price per unit (USD)',
    priceFresh: (when: string) => `Current market price as of ${when}. Change it if you sold at a different price.`,
    priceStale: (price: string, when: string) =>
      `The only price we have is stale (${price} USD, last updated ${when}), so please enter the price you sold at.`,
    priceUnavailable: (reason: string) =>
      `There's no current price (${reason}), so please enter the price you sold at.`,
    priceUnavailableNoReason: "There's no current price, so please enter the price you sold at.",
    fee: 'Fee (USD)',
    executedAt: 'Sold at',
    executedAtHint: 'Defaults to now. Set an earlier date if you sold in the past.',
    required: 'Please fill this in.',
    badNumber: 'Use digits with a dot for decimals, up to 10 decimal places (for example 0.5).',
    mustBePositive: 'Enter an amount above 0.',
    moreThanHeld: (held: string, symbol: string) => `You hold ${held} ${symbol}. Enter ${held} or less.`,
    submit: 'Sell',
    submitting: 'Selling…',
    cancel: 'Cancel',
    sold: (quantity: string, symbol: string) => `Sold ${quantity} ${symbol}. The trade is in Realized trades.`,
    soldAll: (symbol: string) => `That closes your ${symbol} position.`,
    showTrade: 'Show the trade',
    dismiss: 'Dismiss',
  },
  realized: {
    heading: 'Realized trades',
    empty: 'No sells yet. Realized P/L shows up here after your first sale.',
    date: 'Date',
    symbol: 'Symbol',
    quantity: 'Quantity',
    sellPrice: 'Sell price',
    fee: 'Fee',
    averageCost: 'Avg cost at sale',
    proceeds: 'Proceeds',
    realized: 'Realized P/L',
    footnote: 'Proceeds are net of the sell fee. Realized P/L = proceeds − average cost × quantity.',
    newTag: 'new',
  },
  holding: {
    chartComingSoon: 'The price chart for this holding is on its way.',
    backToDashboard: 'Back to the dashboard',
  },
  notFound: {
    title: 'Page not found',
    body: "There's nothing at this address. It may have moved, or the link has a typo.",
  },
  empty: {
    title: 'Your ledger is ready for its first entry',
    body: "Add a buy you've made and MyStocks will keep track of its value, P/L and allocation for you.",
    action: 'Add your first transaction',
  },
  celebration: {
    // One time only, for the first entry. Never tied to gains, losses or trading activity.
    title: 'Your first entry is in the ledger!',
    body: 'From here on, MyStocks keeps the numbers tidy for you.',
    dismiss: 'Close',
  },
  transactions: {
    addHeading: 'Add a buy',
    listHeading: 'Transactions',
    empty: 'Nothing here yet. Your entries will show up in this list.',
    executed: 'Executed',
    symbol: 'Symbol',
    type: 'Type',
    side: 'Side',
    quantity: 'Quantity',
    price: 'Price',
    fee: 'Fee',
    actions: 'Actions',
    delete: 'Delete',
    deleteLabel: (symbol: string, when: string) => `Delete ${symbol} transaction from ${when}`,
    confirmDelete: {
      title: 'Delete this transaction?',
      summary: (side: string, quantity: string, symbol: string, price: string, currency: string, when: string) =>
        `${side} ${quantity} ${symbol} at ${price} ${currency} on ${when}`,
      continue: 'Delete…',
      cancel: 'Cancel',
      confirmTitle: 'Are you sure?',
      confirmBody:
        'This permanently removes the transaction and recalculates your holdings and P/L. It cannot be undone.',
      laterSellsWarning: (symbol: string) =>
        `Careful: you have later sells of ${symbol}. Without this buy they may no longer be covered, and your portfolio will show an error until you fix them.`,
      confirm: 'Yes, delete permanently',
      keep: 'Keep it',
      deleting: 'Deleting…',
      step: (current: number, total: number) => `Step ${current} of ${total}`,
    },
    assetTypes: { stock: 'Stock', crypto: 'Crypto' },
    sides: { buy: 'Buy', sell: 'Sell' },
  },
  form: {
    symbol: 'Symbol',
    symbolPlaceholder: 'Search stocks & crypto',
    type: 'Type',
    executedAt: 'Executed at',
    quantity: 'Quantity',
    price: 'Price (USD)',
    fee: 'Fee (USD)',
    submit: 'Add buy',
    buyOnly: 'Record a buy here. To sell, use the Sell button on a holding in the Dashboard.',
    backdateHint: 'Sold something before you logged the buy? Add the buy with its real date first, then sell it from Holdings.',
    lookingUp: 'Looking up the price…',
    autofillFailed: (message: string) => `Couldn't auto-fill the price: ${message}`,
    enterManually: ' Enter the price manually.',
    livePrice: 'live price',
    closeOn: (date: string) => `${date} close`,
    autoFilled: (price: string, source: string) => `Auto-filled ${price} USD (${source}).`,
    lookedUp: (price: string, source: string) => `Looked-up price: ${price} USD (${source}).`,
    searchUnavailable: (message: string) =>
      `Search unavailable (${message}). Type the symbol and pick its type.`,
    sourceUnavailable: (assetType: 'stock' | 'crypto', detail: string) =>
      `${assetType === 'stock' ? 'Stock' : 'Crypto'} search unavailable: ${detail}`,
  },
  stockData: {
    // Free stock data plans are licensed for personal use; this deployment shows them only to
    // allowlisted accounts.
    notAvailable: "Stock prices aren't available on this deployment.",
    label: 'not available on this deployment',
    searchHint: "Stock search isn't available on this deployment. Type the ticker and choose Stock as the type.",
    autofill: "Stock prices aren't available on this deployment, so please enter the price yourself.",
    sellPrice: "Stock prices aren't available on this deployment, so please enter the price you sold at.",
  },
  attribution: {
    // Wording and link required by CoinGecko's Demo API plan.
    coingecko: 'Data provided by CoinGecko',
    coingeckoUrl: 'https://www.coingecko.com/en/api',
    coingeckoScope: 'Crypto prices: ',
  },
  disclaimer: [
    'Cost basis: average cost; buy fees add to cost, sell fees reduce proceeds. All amounts in USD.',
    'Prices come from free third-party APIs (Finnhub, CoinGecko), are refreshed about once a minute and may be delayed.',
    'For educational and personal tracking use only. Not financial advice.',
  ],
}
